apiVersion: v1
kind: Service
metadata:
  name: elastic-webhook-server
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: elastic-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-webhook-server-cert
