  apiVersion: admissionregistration.k8s.io/v1beta1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: elastic-webhook.k8s.elastic.co
  webhooks:
    - clientConfig:
        caBundle: Cg==
        service:
          name: elastic-webhook-server
          namespace: <NAMESPACE>
          path: /validate-elasticsearch-k8s-elastic-co-v1-elasticsearch
      failurePolicy: Ignore
      name: elastic-es-validation-v1.k8s.elastic.co
      rules:
        - apiGroups:
            - elasticsearch.k8s.elastic.co
          apiVersions:
            - v1
          operations:
            - CREATE
            - UPDATE
          resources:
            - elasticsearches
    - clientConfig:
        caBundle: Cg==
        service:
          name: elastic-webhook-server
          namespace: <NAMESPACE>
          path: /validate-elasticsearch-k8s-elastic-co-v1beta1-elasticsearch
      failurePolicy: Ignore
      name: elastic-es-validation-v1beta1.k8s.elastic.co
      rules:
        - apiGroups:
            - elasticsearch.k8s.elastic.co
          apiVersions:
            - v1beta1
          operations:
            - CREATE
            - UPDATE
          resources:
            - elasticsearches
