  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: logstash-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: logstash-operator
    template:
      metadata:
        labels:
          name: logstash-operator
      spec:
        serviceAccountName: logstash-operator
        containers:
          - name: logstash-operator
            # Replace this with the built image name
            #image: gcr.io/saaspoc-gtso-enterprise-gke/gkegtsoent/logstash-operator/logstash-operator:1.0.0 
            image: docker741/operator-test:v2
            imagePullPolicy: Always
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "logstash-operator"
