apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart-anurag-2
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

      podTemplate:
        spec:
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']

      
## empty pod template      
    # podTemplate:
    #   spec:
    #     volumes:
    #     - name: elasticsearch-data
    #       emptyDir: {}

## could not make it work: volumeClaimTemplates
    # volumeClaimTemplates:
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 1Gi
    #     storageClassName: standard

## this will creat a loadBalancer service type for these ES cluster
  # http:
  #   service:
  #     spec:
  #       type: LoadBalancer

## got applied not sure how to test: transport service
  # transport:
  #   service:
  #     metadata:
  #       labels:
  #         my-custom: label
  #     spec:
  #       type: LoadBalancer



    