apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: logstashes.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Logstash
    listKind: LogstashList
    plural: logstashes
    singular: logstash
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      #x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true

